name: test via Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y nasm grub-pc-bin grub-common xorriso

    - name: You compile it with my fucking compiler
      run: make all

    - name: Create ISO
      run: make iso

    - name: Upload all da build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: qinu-nightly
        path: build

